@rootUrl = http://localhost:9002

#API list 

### Check server status
GET {{rootUrl}}


###Auth API

###create new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type:application/json

{
"fName":"Arzin",
"lName":"Shrestha",
"email":"arz@gmail.com",
"password": "1234"
}
 
####login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type:application/json

{"email":"anu@gmail.com",
"password": "1234"}